export const PRODUCTS_START = 'PRODUCTS_START';
export const PRODUCTS_COMPLETE = 'PRODUCTS_COMPLETE';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const UPDATE_PRODUCTS_STAR = 'UPDATE_PRODUCTS_STAR';
export const LIST_PRODUCTS_STAR = 'LIST_PRODUCTS_STAR';
export const LIST_PRODUCTS_COMPLETE = 'LIST_PRODUCTS_COMPLETE';